[package]
name = "baphomet"
version = "0.1.0"
edition = "2024"

[dependencies]
colog = "1.3.0"
gl = "0.14.0"
sdl3 = { git = "https://github.com/cynicalico/sdl3-rs", branch = "pixel_size_changed" }
log = "0.4.26"
nalgebra-glm = "0.19.0"
pastey = "0.1.0"
rand = "0.9.0"
regex = "1.11.1"
